#ifndef __CONFIG_H__
#define __CONFIG_H__

#define RENDER_SCALE 10

#define PAUSE_KEY SDL_SCANCODE_SPACE

#define CHIP8_KEY_0 SDL_SCANCODE_X
#define CHIP8_KEY_1 SDL_SCANCODE_1
#define CHIP8_KEY_2 SDL_SCANCODE_2
#define CHIP8_KEY_3 SDL_SCANCODE_3
#define CHIP8_KEY_4 SDL_SCANCODE_Q
#define CHIP8_KEY_5 SDL_SCANCODE_W
#define CHIP8_KEY_6 SDL_SCANCODE_E
#define CHIP8_KEY_7 SDL_SCANCODE_A
#define CHIP8_KEY_8 SDL_SCANCODE_S
#define CHIP8_KEY_9 SDL_SCANCODE_D
#define CHIP8_KEY_A SDL_SCANCODE_Z
#define CHIP8_KEY_B SDL_SCANCODE_C
#define CHIP8_KEY_C SDL_SCANCODE_4
#define CHIP8_KEY_D SDL_SCANCODE_R
#define CHIP8_KEY_E SDL_SCANCODE_F
#define CHIP8_KEY_F SDL_SCANCODE_V

#endif
